# Name(s)
**Ethan Moore and Ajay Patel**

**Instructions:** This is an individual assignment, but you may discuss your code with your neighbors.

# Python and NumPy

While other IDEs exist for Python development and for data science related activities, one of the most popular environments is Jupyter Notebooks.

This lab is not intended to teach you everything you will use in this course. Instead, it is designed to give you exposure to some critical components from NumPy that we will rely upon routinely.

## Exercise 0
Please read and reference the following as your progress through this course. 

* [What is the Jupyter Notebook?](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb#)
* [Notebook Tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)
* [Notebook Basics](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb)

**In the space provided below, what are three things that still remain unclear or need further explanation?**

1. Is there a shortcut to immediately add or delete cells?

2. Is there an easy way to convert work done in a .ipynb file to a .py file?

3. What are containers to run software? And do we need them in this course?

## Exercises 1-7
For the following exercises please read the Python appendix in the Marsland textbook and answer problems A.1-A.7 in the space provided below.

## Exercise 1

In [1]:
# YOUR SOLUTION HERE
#a=1000
# print('this is my answer',a+1) 
import numpy as np

a = np.array([[2,2,2,2]] * 6)
a

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

## Exercise 2

In [2]:
# YOUR SOLUTION HERE\
c = np.array([[1,1,1,1]] * 6)
d = np.eye(6,4)

b = d + d + c
b

array([[3., 1., 1., 1.],
       [1., 3., 1., 1.],
       [1., 1., 3., 1.],
       [1., 1., 1., 3.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Exercise 3

In [3]:
# YOUR SOLUTION HERE

a * b

#This is the code below to answer part 2
# np.dot(a,b)

array([[6., 2., 2., 2.],
       [2., 6., 2., 2.],
       [2., 2., 6., 2.],
       [2., 2., 2., 6.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

a * b works because the dimensions of the two matrices are the same. 

np.dot(a,b) does not work because the number of columns in the matrix a is not the same as the number of rows in matrix b

## Exercise 4

In [4]:
# YOUR SOLUTION HERE

print(np.dot(a.transpose(), b))
print("")
print(np.dot(a, b.transpose()))

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]

[[12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]]


The results are different shapes because the first matrix multiplication is fit to be made a product that is a 4x4 matrix and the second matrix result is a 6x6 for the same reason

## Exercise 5

In [5]:
# YOUR SOLUTION HERE
print("Hello World")

Hello World


## Exercise 6

In [6]:
# YOUR SOLUTION HERE

arr = np.random.randint(0,100,10)
print("mean:", arr.mean())
print("standard deviation:", arr.std())
print("max:", arr.max())
print("min:", arr.min())
print("sum:", arr.sum())


mean: 61.3
standard deviation: 26.548257946614875
max: 89
min: 12
sum: 613


## Exercise 7

In [7]:
# YOUR SOLUTION HERE

def count_1s(arr):
    count  = 0
    for i in range(len(arr)):
        if arr[i] == 1:
            count += 1 
    print(count)

print(arr)
print("Number of 1s:")
count_1s(arr)

print(np.where(arr == 1, 1, 0).sum())

[77 89 86 21 84 54 55 86 49 12]
Number of 1s:
0
0


## Excercises 8-???
While the Marsland book avoids using another popular package called Pandas, we will use it at times throughout this course. Please read and study [10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) before proceeding to any of the exercises below.

## Exercise 8
Repeat exercise A.1 from Marsland, but create a Pandas DataFrame instead of a NumPy array.

In [8]:
# YOUR SOLUTION HERE
import pandas as pd

a = pd.DataFrame({
    "A" : pd.Series(2, index=list(range(6))),
    "B" : pd.Series(2, index=list(range(6))),
    "C" : pd.Series(2, index=list(range(6))),
    "D" : pd.Series(2, index=list(range(6)))
})

print(a)

   A  B  C  D
0  2  2  2  2
1  2  2  2  2
2  2  2  2  2
3  2  2  2  2
4  2  2  2  2
5  2  2  2  2


## Exercise 9
Repeat exercise A.2 using a DataFrame instead.

In [9]:
# YOUR SOLUTION HERE

b = pd.DataFrame({
    "A" : np.array([3, 1, 1, 1, 1, 1]),
    "B" : np.array([1, 3, 1, 1, 1, 1]),
    "C" : np.array([1, 1, 3, 1, 1, 1]),
    "D" : np.array([1, 1, 1, 3, 1, 1])
})

print(b)

   A  B  C  D
0  3  1  1  1
1  1  3  1  1
2  1  1  3  1
3  1  1  1  3
4  1  1  1  1
5  1  1  1  1


## Exercise 10
Repeat exercise A.3 using DataFrames instead.

In [10]:
# YOUR SOLUTION HERE

print(a * b)

# This is the code below to answer part 2
# print(a.dot(b))

   A  B  C  D
0  6  2  2  2
1  2  6  2  2
2  2  2  6  2
3  2  2  2  6
4  2  2  2  2
5  2  2  2  2


a * b works because the product is the result of the same position in each dataframe being multiplied together.

a.dot(b) does not work because dataframe a does not have the same number of columns as the number of rows in dataframe b.

## Exercise 11
Repeat exercise A.7 using a dataframe.

In [11]:
# YOUR SOLUTION HERE


def count_1s(df):
    count  = 0
    for i in range(len(df)):
        if arr[i] == 1:
            count += 1 
    print(count)

print(a)
print("")
print("Number of 1's: ")
count_1s(a)

print("")
print(np.where(a == 1, 1, 0).sum())

   A  B  C  D
0  2  2  2  2
1  2  2  2  2
2  2  2  2  2
3  2  2  2  2
4  2  2  2  2
5  2  2  2  2

Number of 1's: 
0

0


## Exercises 12-14
Now let's look at a real dataset, and talk about ``.loc``. For this exercise, we will use the popular Titanic dataset from Kaggle. Here is some sample code to read it into a dataframe.

In [12]:
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv"
)
titanic_df

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000      0      0   24160  211.3375       B5        S    2   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.0000      1      2  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000      1      2  113781  151.5500  C22 C26        S  NaN   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.5000      1      0    2665   14.4542      NaN        C  NaN   
1305  female      NaN      1      0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000      0      0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000      0      0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000      0      0  315082    7.8750      NaN        S  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1304  328.0                              NaN  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  

[1309 rows x 14 columns]

Notice how we have nice headers and mixed datatypes? That is one of the reasons we might use Pandas. Please refresh your memory by looking at the 10 minutes to Pandas again, but then answer the following.

## Exercise 12
How do you select the ``name`` column without using .iloc?

In [13]:
## YOUR SOLUTION HERE

titanic_df[["name"]].head()

name
0                    Allen, Miss. Elisabeth Walton
1                   Allison, Master. Hudson Trevor
2                     Allison, Miss. Helen Loraine
3             Allison, Mr. Hudson Joshua Creighton
4  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)

## Exercise 13
After setting the index to ``sex``, how do you select all passengers that are ``female``? And how many female passengers are there?

In [14]:
## YOUR SOLUTION HERE
titanic_df.set_index('sex',inplace=True)

In [15]:
titanic_df.loc["female"].head()

pclass  survived                                             name  \
sex                                                                         
female       1         1                    Allen, Miss. Elisabeth Walton   
female       1         0                     Allison, Miss. Helen Loraine   
female       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
female       1         1                Andrews, Miss. Kornelia Theodosia   
female       1         1    Appleton, Mrs. Edward Dale (Charlotte Lamson)   

         age  sibsp  parch  ticket      fare    cabin embarked boat  body  \
sex                                                                         
female  29.0      0      0   24160  211.3375       B5        S    2   NaN   
female   2.0      1      2  113781  151.5500  C22 C26        S  NaN   NaN   
female  25.0      1      2  113781  151.5500  C22 C26        S  NaN   NaN   
female  63.0      1      0   13502   77.9583       D7        S   10   NaN   
female  53.0      2      0   11769   51.4792     C101        S    D   NaN   

                              home.dest  
sex                                      
female                     St Louis, MO  
female  Montreal, PQ / Chesterville, ON  
female  Montreal, PQ / Chesterville, ON  
female                       Hudson, NY  
female              Bayside, Queens, NY

In [16]:
print(len(titanic_df.loc["female"]))

466


## Exercise 14
How do you reset the index?

In [17]:
## YOUR SOLUTION HERE
titanic_df.reset_index().head()

sex  pclass  survived                                             name  \
0  female       1         1                    Allen, Miss. Elisabeth Walton   
1    male       1         1                   Allison, Master. Hudson Trevor   
2  female       1         0                     Allison, Miss. Helen Loraine   
3    male       1         0             Allison, Mr. Hudson Joshua Creighton   
4  female       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON